version: '3.7'

services:
  lyrics-service:
    image: ${GCR_REGISTRY}/mbm/lyrics-service:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    volumes:
      - ..\src\main\resources\lyrics-service-key.json:/src/main/resources/lyrics-service-key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/src/main/resources/lyrics-service-key.json
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
